name: Build Windows exe (GUI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt ( pip install -r requirements.txt )
          pip install pyinstaller

      - name: Build (PyInstaller GUI)
        run: |
          pyinstaller --noconfirm --onefile --windowed --name app_gui main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_gui-exe
          path: dist/app_gui.exe
